// This stays relative to the Quartz checkout so the locally linked plugin uses
// Quartz's single Preact instance without needing its own node_modules tree.
import { h } from "../../node_modules/preact/dist/preact.mjs"

const CSS = `
.quartztoc{--scroll-amount:0;--thumb-amount:0;display:flex;flex:1 1 0;flex-direction:column;align-self:stretch;min-height:0;width:100%;font-family:var(--bodyFont);font-size:.85rem;line-height:1.3;position:relative}.quartztoc.desktop-only{display:flex}@media(max-width:800px){.quartztoc.desktop-only{display:none}}.quartztoc-track{position:relative;flex:1 1 0;min-height:0;width:100%}.quartztoc-track::before{content:"";position:absolute;inset:0 auto 0 0;width:1px;background:var(--lightgray)}.quartztoc-rail-thumb{position:absolute;left:-1px;width:3px;top:calc(var(--scroll-amount)*1%);height:calc(var(--thumb-amount)*1%);background:var(--gray);border-radius:2px}.quartztoc .toc-row{position:absolute;left:0;right:0;top:calc(var(--toc-top,0)*1%);display:flex;align-items:flex-start}.quartztoc .toc-level-2 .toc-link{padding-left:12px}.quartztoc .toc-level-3 .toc-link{padding-left:24px;font-size:.92em}.quartztoc .toc-level-4 .toc-link{padding-left:36px;font-size:.92em}.quartztoc .toc-level-5 .toc-link{padding-left:48px;font-size:.88em}.quartztoc .toc-level-6 .toc-link{padding-left:60px;font-size:.88em}.quartztoc .toc-row-title .toc-text{font-family:var(--headerFont);font-weight:500;font-size:.95rem}.quartztoc .toc-dot{flex-shrink:0;width:7px;height:7px;margin-left:-3px;margin-top:.45em;margin-right:9px;box-shadow:0 0 0 2px var(--light);opacity:.55;transition:background-color .2s,opacity .2s,transform .2s}.quartztoc .toc-level-3 .toc-dot,.quartztoc .toc-level-4 .toc-dot{width:5px;height:5px;margin-left:-2px;opacity:.4}.quartztoc .toc-level-5 .toc-dot,.quartztoc .toc-level-6 .toc-dot{width:4px;height:4px;margin-left:-1.5px;opacity:.35}.quartztoc .toc-link{display:inline-block;max-width:calc(100% - 16px);overflow:hidden;color:var(--gray);line-height:1.3;opacity:0;text-decoration:none!important;text-overflow:ellipsis;white-space:nowrap;transition:color .25s ease,opacity .25s ease}.quartztoc:hover .toc-link{opacity:.85;white-space:normal;overflow:visible;text-overflow:clip}.quartztoc .toc-row.is-active .toc-dot{opacity:1;box-shadow:0 0 0 2px var(--light)}.quartztoc .toc-row.is-active .toc-link{color:var(--dark);font-weight:500;opacity:1;white-space:normal;overflow:visible;text-overflow:clip}
`

const RUNTIME = `
(function(){var TOP="__top__",cleanup;function setup(){cleanup&&cleanup();var toc=document.getElementById("quartztoc"),article=document.querySelector("article");if(!toc)return;var rows=[...toc.querySelectorAll(".toc-row[data-for]")],bySlug=new Map,headings=[];rows.forEach(r=>{var s=r.dataset.for;bySlug.set(s,r);var el=s!==TOP&&document.getElementById(s);el&&headings.push({s,el})});var active;function set(s){if(s===active)return;active&&bySlug.get(active)?.classList.remove("is-active");s&&bySlug.get(s)?.classList.add("is-active");active=s}function position(){var title=bySlug.get(TOP);title&&(title.style="--toc-top:0");if(!article)return;var rect=article.getBoundingClientRect(),top=rect.top+scrollY,height=rect.height;headings.forEach(({s,el})=>{var offset=Math.max(0,el.getBoundingClientRect().top+scrollY-top);bySlug.get(s).style.setProperty("--toc-top",Math.min(100,offset/height*100))})}function refresh(){var next=TOP;headings.forEach(({s,el})=>{if(el.getBoundingClientRect().top+el.offsetHeight/2<=innerHeight*.35)next=s});set(next);if(article){var rect=article.getBoundingClientRect(),amount=Math.max(2,Math.min(100,innerHeight/rect.height*100)),progress=Math.max(0,Math.min(1,-rect.top/Math.max(1,rect.height-innerHeight)));toc.style.setProperty("--thumb-amount",amount);toc.style.setProperty("--scroll-amount",progress*(100-amount))}}var scroll=()=>requestAnimationFrame(refresh),resize=()=>{position();scroll()};document.addEventListener("scroll",scroll,{passive:true});window.addEventListener("resize",resize);toc.querySelectorAll("a[data-for]").forEach(a=>a.addEventListener("click",e=>{e.preventDefault();var s=a.dataset.for,el=s===TOP?document.body:document.getElementById(s);el?.scrollIntoView({behavior:"smooth",block:"start"});history.pushState(null,"",s===TOP?"#":"#"+s)}));position();refresh();cleanup=()=>{document.removeEventListener("scroll",scroll);window.removeEventListener("resize",resize)}}document.addEventListener("nav",setup);document.readyState==="loading"?document.addEventListener("DOMContentLoaded",setup,{once:true}):setup()})()
`

export function TalitaTOC() {
  function Component({ fileData, displayClass }) {
    const entries = fileData?.toc
    if (!Array.isArray(entries) || entries.length === 0) return null
    const rows = []
    const add = (slug, level, text) => rows.push(h("div", { class: `toc-row toc-level-${level}`, "data-for": slug, key: slug }, h("div", { class: "toc-dot", "aria-hidden": "true" }), h("a", { class: "toc-link", href: slug === "__top__" ? "#" : `#${slug}`, "data-for": slug }, h("span", { class: "toc-text" }, text))))
    if (fileData.frontmatter?.title) add("__top__", 2, fileData.frontmatter.title)
    entries.forEach((entry) => add(String(entry.slug), Math.min(6, Math.max(2, Number(entry.depth) + 1)), String(entry.text)))
    return h("div", { class: [displayClass, "quartztoc"].filter(Boolean).join(" "), id: "quartztoc" }, h("div", { class: "quartztoc-track" }, h("div", { class: "quartztoc-rail-thumb", "aria-hidden": "true" }), rows))
  }
  Component.displayName = "TalitaTOC"
  Component.css = CSS
  Component.afterDOMLoaded = RUNTIME
  return Component
}
